// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kammxhojbhluiwopvqzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthbW14aG9qYmhsdWl3b3B2cXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzU1ODQsImV4cCI6MjA2MDExMTU4NH0.oqGBLe7NSSmHnqgGgkdMw-NIHBUd0sbbIx66D3BCpyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);